server:
  port: 8222 #服务端口
spring:
  application:
    name: service-gateway #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置nacos服务的ip：端口
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址（静态路由写法）
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址(动态路由写法（推荐）)
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
            - After=2021-04-05T19:59:49.192+08:00[Asia/Shanghai] #服务开启时间
            #- Before=2021-04-05T19:59:49.192+08:00[Asia/Shanghai] #服务最后结束时间
            #- Between=2021-04-05T19:59:49.192+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy  #cmd里使用命令curl http://localhost:9527/payment/get/1 --cookie "username=zzyy"
            #- Header=X-Request-Id,\d+ #curl http://localhost:9527/payment/get/1 -H "X-Request-Id:123"
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username,\d+ #要有参数名username并且还要是整数才能路由
        #          filters: #配置过滤器（并不一定用来做拦截）
        #             -AddRequestHeader=X-Request-Foo,Bar #给该请求添加一个名为X-Request-Foo的请求头，值为Bar

        - id: service-user
          uri: lb://service-user #路由
          predicates: #断言
            - Path=/userService/** #断言：路径相匹配的进行路由
        - id: service-sms
          uri: lb://service-sms #路由
          predicates: #断言
            - Path=/smsService/** #断言：路径相匹配的进行路由
        - id: service-blog
          uri: lb://service-blog #路由
          predicates: #断言
            - Path=/blogService/** #断言：路径相匹配的进行路由
        - id: service-oss
          uri: lb://service-oss #路由
          predicates: #断言
            - Path=/ossService/** #断言：路径相匹配的进行路由
        - id: service-vod
          uri: lb://service-vod #路由
          predicates: #断言
            - Path=/vodService/** #断言：路径相匹配的进行路由

